"""🔒 The incoming folder is strictly read-only — enforced here, not just documented.

The owner's raw subs live in ``incoming/`` and **nowhere else**: no backup, no
second copy. A single stray ``unlink``/``move`` there destroys data that cannot
be regenerated by any amount of re-stacking. ``AGENTS.md`` §10 carries the prose
rule, but a prose rule is not enforcement — the next agent to build a "tidy up
your incoming folder" or "free space by removing the originals you've already
ingested" feature is exactly the failure mode this file exists to catch, in CI,
before it can ever reach the owner's NAS.

Three layers, deliberately overlapping, because each catches what the others miss:

1. :func:`_snapshot` / :func:`_assert_unchanged` — a **behavioural** check. Seed a
   realistic incoming tree, drive the real code paths that could plausibly touch
   it (scan → ingest → QC → stack, the storage clears, run prune, target merge,
   ``DELETE`` a target *with* ``remove_files=true``, sample-data load/remove,
   reprocess-all, the video pipeline), then assert every seeded file still exists
   with an unchanged size, checksum **and** mtime, and that the directory listing
   itself is unchanged. This catches real behaviour, not spelling.
2. :class:`_IncomingSentinel` — a **call-level spy**. Every destructive stdlib
   entry point (``os.remove``/``unlink``/``rmdir``/``truncate``, ``os.rename``/
   ``replace``, ``Path.unlink``/``rmdir``/``rename``/``replace``, ``shutil.move``/
   ``rmtree``/``copy*``) is wrapped for the duration of the run and **fails the
   test if it is called with a path that resolves inside the incoming folder**.
   Stronger than grepping source text: it sees the call whatever module or alias
   made it, and it fires even when the file happened not to exist yet.
3. :func:`test_ingest_still_copies_and_never_moves` — a **source** check on the
   one function where the tempting "optimisation" lives, so the classic
   `copy2` → `move` regression is caught at the line that would introduce it.

The only writes ever permitted under ``incoming/`` are the upload endpoints
*adding* new files (they skip a name that already exists — pinned below), and the
``.part`` temp sidecar each upload streams into and owns end to end. Everything
else is a violation, by construction.

If a test here fails: **do not relax it.** Find the call it caught and remove it.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # tests/ for synth
from synth import write_seestar_fits  # noqa: E402


# --------------------------------------------------------------------------- #
# Layer 1 — the behavioural snapshot
# --------------------------------------------------------------------------- #

def _snapshot(root: Path) -> dict[str, tuple[int, str, int]]:
    """Every file under ``root`` → (size, sha256, mtime_ns).

    mtime is included deliberately: a rewrite that happened to reproduce the same
    bytes is still the app writing into a folder it must only read.
    """
    out: dict[str, tuple[int, str, int]] = {}
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        st = p.stat()
        out[str(p.relative_to(root))] = (
            st.st_size, hashlib.sha256(p.read_bytes()).hexdigest(), st.st_mtime_ns)
    return out


def _assert_unchanged(before: dict, root: Path, what: str) -> None:
    after = _snapshot(root)
    lost = sorted(set(before) - set(after))
    assert not lost, (
        f"{what}: {len(lost)} file(s) VANISHED from the incoming folder — {lost[:5]}. "
        "The owner's raw subs exist there and nowhere else (AGENTS.md §10); this is "
        "unrecoverable data loss, not a test to relax.")
    changed = sorted(k for k in before if after[k] != before[k])
    assert not changed, (
        f"{what}: {len(changed)} file(s) were MODIFIED in place in the incoming "
        f"folder — {changed[:5]}. The app may only read there (AGENTS.md §10).")
    assert set(after) == set(before), (
        f"{what}: the incoming listing changed — unexpected new entries "
        f"{sorted(set(after) - set(before))[:5]}.")


# --------------------------------------------------------------------------- #
# Layer 2 — the call-level spy
# --------------------------------------------------------------------------- #

# An upload streams into a unique ``<name>.<rand>.part`` sidecar next to its
# destination and atomically renames it into place; a failed upload removes its
# own sidecar. That temp is created, owned and cleaned up by the same request, so
# it is the one path under incoming the app is allowed to delete or rename. It is
# never a user file: the scanner's FITS glob skips ``.part`` entirely.
def _is_own_upload_temp(p: Path) -> bool:
    return p.suffix == ".part"


class _IncomingSentinel:
    """Wraps the destructive stdlib calls and records any that reach ``incoming``."""

    def __init__(self, incoming: Path) -> None:
        self.root = incoming.resolve()
        self.violations: list[str] = []

    def _inside(self, path) -> Path | None:  # noqa: ANN001
        """The resolved path if it lands under incoming, else ``None``.

        Symlinks and ``..`` are resolved first — a NAS mount symlinked into the
        data root must not be a way around the rule.
        """
        try:
            p = Path(os.fspath(path)).resolve()
        except (OSError, TypeError, ValueError):
            return None
        return p if p == self.root or self.root in p.parents else None

    def _flag(self, call: str, path) -> None:  # noqa: ANN001
        p = self._inside(path)
        if p is not None and not _is_own_upload_temp(p):
            self.violations.append(f"{call}({p})")

    def _flag_overwrite(self, call: str, dst) -> None:  # noqa: ANN001
        """A *destination* inside incoming is only legal if nothing is there.

        ``os.replace``/``shutil.copy*`` silently clobber an existing file, so
        "the app only ever adds" has to mean the target did not exist.
        """
        p = self._inside(dst)
        if p is not None and p.exists() and not _is_own_upload_temp(p):
            self.violations.append(f"{call}(→ {p}) would overwrite an existing file")

    def arm(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # (module/class, attribute) pairs. Patching the *attribute* catches the
        # ``os.remove(...)`` / ``p.unlink()`` call styles the codebase uses.
        for owner, name in ((os, "remove"), (os, "unlink"), (os, "rmdir"),
                            (os, "truncate"), (shutil, "rmtree"),
                            (Path, "unlink"), (Path, "rmdir")):
            self._wrap_target(monkeypatch, owner, name)
        for owner, name in ((os, "rename"), (os, "replace"), (shutil, "move"),
                            (Path, "rename"), (Path, "replace")):
            self._wrap_move(monkeypatch, owner, name)
        for name in ("copy", "copy2", "copyfile"):
            self._wrap_copy(monkeypatch, shutil, name)

    def _label(self, owner, name: str) -> str:  # noqa: ANN001
        return f"{getattr(owner, '__name__', owner.__class__.__name__)}.{name}"

    def _wrap_target(self, monkeypatch, owner, name) -> None:  # noqa: ANN001
        orig, label = getattr(owner, name), self._label(owner, name)

        def guard(path, *a, **kw):  # noqa: ANN001 — `path` is self for Path methods
            self._flag(label, path)
            return orig(path, *a, **kw)

        monkeypatch.setattr(owner, name, guard)

    def _wrap_move(self, monkeypatch, owner, name) -> None:  # noqa: ANN001
        orig, label = getattr(owner, name), self._label(owner, name)

        def guard(src, dst, *a, **kw):  # noqa: ANN001
            self._flag(label, src)          # moving a file *out* of incoming
            self._flag_overwrite(label, dst)  # or clobbering one still in it
            return orig(src, dst, *a, **kw)

        monkeypatch.setattr(owner, name, guard)

    def _wrap_copy(self, monkeypatch, owner, name) -> None:  # noqa: ANN001
        orig, label = getattr(owner, name), self._label(owner, name)

        def guard(src, dst, *a, **kw):  # noqa: ANN001
            self._flag_overwrite(label, dst)
            return orig(src, dst, *a, **kw)

        monkeypatch.setattr(owner, name, guard)

    def assert_clean(self, what: str) -> None:
        assert not self.violations, (
            f"{what}: {len(self.violations)} destructive call(s) reached the "
            f"incoming folder — {self.violations[:5]}. The owner's only copy of "
            "their raw subs lives there (AGENTS.md §10): the app may read and "
            "create-new, never delete, move, rename, truncate or overwrite.")


@pytest.fixture
def sentinel(data_root: Path, monkeypatch: pytest.MonkeyPatch) -> _IncomingSentinel:
    """Arm the spy before anything else in the test touches the app."""
    s = _IncomingSentinel(data_root / "incoming")
    s.arm(monkeypatch)
    return s


# --------------------------------------------------------------------------- #
# Decoys — a realistic incoming tree the app has no business editing
# --------------------------------------------------------------------------- #

def _seed_decoys(incoming: Path) -> None:
    """Add the shapes the fixture's two clean target folders don't cover.

    The ``data_root`` fixture already lays down ``M_42/`` and ``NGC_7000/`` with
    three Seestar subs each; these add a Seestar ``_sub`` folder, a bare on-device
    output folder, a stray non-FITS file, and a loose sub at the top level — i.e.
    the cases the scanner classifies differently, so a "clean up what I skipped"
    bug would surface here first.
    """
    sub = incoming / "M 51_sub"
    sub.mkdir(parents=True, exist_ok=True)
    for i in range(2):
        write_seestar_fits(sub / f"Light_M 51_10.0s_IRCUT_2026{i:02d}.fit",
                           width=64, height=48, n_stars=8, seed=7 + i)
    bare = incoming / "M 51"
    bare.mkdir(parents=True, exist_ok=True)
    write_seestar_fits(bare / "Stacked_60_M 51.fit", width=64, height=48,
                       n_stars=8, seed=21)
    (incoming / "M_42" / "capture-notes.txt").write_text("clear night, no moon\n")
    write_seestar_fits(incoming / "loose_frame.fit", width=64, height=48,
                       n_stars=8, seed=33)
    # Backdate everything: an mtime from "last night" makes an accidental
    # rewrite obvious rather than hiding inside the test's own second.
    old = time.time() - 86_400
    for p in incoming.rglob("*"):
        if p.is_file():
            os.utime(p, (old, old))


def _wait_job(client, job_id: str, timeout: float = 180.0) -> dict:
    deadline = time.time() + timeout
    while time.time() < deadline:
        body = client.get(f"/api/jobs/{job_id}").json()
        if body["state"] in ("done", "error", "cancelled", "interrupted"):
            return body
        time.sleep(0.05)
    raise AssertionError(f"job {job_id} did not finish in {timeout}s")


# --------------------------------------------------------------------------- #
# The tests
# --------------------------------------------------------------------------- #

def test_the_sentinel_actually_fires(sentinel, data_root):
    """Meta-test: prove the spy works, so a green run above means something.

    Without this, a sentinel that silently stopped wrapping anything would let
    every other test in this file pass while enforcing nothing.
    """
    victim = data_root / "incoming" / "M_42" / "frame_000.fit"
    assert victim.exists()
    victim.unlink()
    assert sentinel.violations, "the sentinel did not notice a deletion in incoming"
    assert "frame_000.fit" in sentinel.violations[0]
    with pytest.raises(AssertionError, match="incoming folder"):
        sentinel.assert_clean("meta")

    # …and it stays quiet for the app's own storage, and for an upload sidecar.
    sentinel.violations.clear()
    (data_root / "library").mkdir(parents=True, exist_ok=True)
    scratch = data_root / "library" / "scratch.bin"
    scratch.write_bytes(b"x")
    scratch.unlink()
    part = data_root / "incoming" / "M_42" / "frame_001.fit.abc.part"
    part.write_bytes(b"x")
    part.unlink()
    sentinel.assert_clean("app-owned paths")


def test_the_whole_workflow_never_deletes_or_edits_a_file_in_incoming(
        sentinel, data_root, client):
    """Drive the real destructive-looking paths end to end and check the folder.

    This is the one that would have caught a "free up space by removing ingested
    originals" feature: every endpoint below either deletes something or walks
    the incoming tree, and none of them may leave a mark on it.
    """
    incoming = data_root / "incoming"
    _seed_decoys(incoming)
    before = _snapshot(incoming)
    assert len(before) >= 10, "the decoy tree should be non-trivial"

    # Stage-1 caching ON. This is the setting that makes ingest *copy each source
    # frame*, so it is the branch where a "move it instead, we've got a copy now"
    # optimisation would live — off by default, and therefore unexercised (and
    # unguarded) unless the test asks for it explicitly.
    assert client.put("/api/settings", json={"copy_to_cache": True}).status_code == 200

    # Scan → ingest → QC (the hot path that reads every file in the folder).
    job = _wait_job(client, client.post("/api/scan").json()["job_id"])
    assert job["state"] == "done", job.get("error")
    _assert_unchanged(before, incoming, "after scan/ingest/QC")

    targets = [t["safe_name"] for t in client.get("/api/targets").json()]
    assert targets, "the scan should have produced targets to operate on"

    # Sample data — loaded and then removed with remove_files=True.
    assert client.post("/api/sample").status_code == 201
    assert client.delete("/api/sample").status_code == 200

    # A full process (QC + solve + stack) on one target, then prune its runs.
    _wait_job(client, client.post(f"/api/targets/{targets[0]}/process").json()["job_id"])
    client.post(f"/api/targets/{targets[0]}/stack-runs/prune", json={"keep": 0})

    # Every clearable cache stage.
    for stage in ("stage1", "stage2", "thumbs", "all"):
        r = client.post(f"/api/targets/{targets[0]}/cache/clear", params={"stage": stage})
        assert r.status_code == 200, r.text

    # Merge two targets into one, then delete the survivor *with its files*.
    if len(targets) > 1:
        client.post("/api/targets/merge",
                    json={"into": targets[0], "sources": [targets[1]]})
    r = client.delete(f"/api/targets/{targets[0]}", params={"remove_files": "true"})
    assert r.status_code == 200, r.text

    # Re-scan afterwards: the frames must still be there to find, which is the
    # whole point — a user can always rebuild their library from incoming.
    job = _wait_job(client, client.post("/api/scan").json()["job_id"])
    assert job["state"] == "done", job.get("error")
    assert client.get("/api/targets").json(), "re-scan found nothing to rebuild from"

    _assert_unchanged(before, incoming, "after the full destructive workflow")
    sentinel.assert_clean("the full destructive workflow")


def test_reprocess_all_leaves_the_source_frames_alone(sentinel, data_root, client):
    """Reprocess-everything walks every target and restacks it — a batch job is
    exactly where a "tidy up as you go" step would be tempting to add."""
    incoming = data_root / "incoming"
    _seed_decoys(incoming)
    _wait_job(client, client.post("/api/scan").json()["job_id"])
    before = _snapshot(incoming)

    r = client.post("/api/reprocess-all")
    assert r.status_code in (200, 202, 409), r.text
    if r.status_code < 300 and "job_id" in r.json():
        _wait_job(client, r.json()["job_id"])

    _assert_unchanged(before, incoming, "after reprocess-all")
    sentinel.assert_clean("reprocess-all")


def test_uploading_a_name_that_already_exists_never_overwrites_the_original(
        sentinel, data_root, client):
    """Upload is the one endpoint allowed to *write* under incoming — it may only
    ever add. A same-named sub is reported as skipped, byte-for-byte intact."""
    incoming = data_root / "incoming"
    _seed_decoys(incoming)
    existing = incoming / "M_42" / "frame_000.fit"
    before = _snapshot(incoming)

    original = existing.read_bytes()
    r = client.post("/api/upload", files={"files": ("frame_000.fit", b"NOT A FITS")},
                    data={"target": "M_42"})
    assert r.status_code in (200, 201), r.text
    assert [f["name"] for f in r.json()["skipped"]] == ["frame_000.fit"]
    assert r.json()["saved"] == []
    assert existing.read_bytes() == original

    _assert_unchanged(before, incoming, "after a colliding upload")
    sentinel.assert_clean("a colliding upload")

    # A genuinely new name is added — and adding is all it does.
    r = client.post("/api/upload", files={"files": ("brand_new.fit", b"hello")},
                    data={"target": "M_42"})
    assert r.status_code in (200, 201), r.text
    assert [f["name"] for f in r.json()["saved"]] == ["brand_new.fit"]
    added = {**before, "M_42/brand_new.fit": _snapshot(incoming)["M_42/brand_new.fit"]}
    _assert_unchanged(added, incoming, "after a fresh upload")
    sentinel.assert_clean("a fresh upload")

    # A zipped capture folder: unpacked in place, its own bytes never kept — the
    # ``.part`` sidecar it streams through is the one temp the app owns there.
    import io
    import zipfile

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("M 63_sub/Light_M 63_10.0s.fit", b"zipped sub")
    r = client.post("/api/upload", files={"files": ("drop.zip", buf.getvalue())},
                    data={"target": ""})
    assert r.status_code in (200, 201), r.text
    _assert_unchanged({**added, **{k: v for k, v in _snapshot(incoming).items()
                                   if k.startswith("M 63_sub/")}},
                      incoming, "after a zip upload")
    sentinel.assert_clean("a zip upload")


def test_the_video_pipeline_never_touches_the_capture_it_stacks(
        sentinel, data_root, client):
    """Moon & Sun decodes a clip *in place* out of incoming and crops the result
    in the app's own store. The source clip must come back untouched — including
    across the in-place crop and undo, which rewrite the finished still."""
    from seestack.video.ffmpeg import ffmpeg_available

    if not ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not installed (see AGENTS.md §7)")

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from videosynth import lunar_video

    cap = data_root / "incoming" / "Lunar_video"
    cap.mkdir(parents=True, exist_ok=True)
    lunar_video(cap / "clip.mp4", n_frames=10, sharp_indices=(1, 4, 7), w=64, h=48)
    _seed_decoys(data_root / "incoming")
    before = _snapshot(data_root / "incoming")

    job = _wait_job(client, client.post("/api/videos/Lunar_video/stack",
                                        json={"keep_percent": 30}).json()["job_id"])
    assert job["state"] == "done", job.get("error")
    client.post("/api/videos/Lunar_video/crop")
    client.post("/api/videos/Lunar_video/uncrop")

    _assert_unchanged(before, data_root / "incoming", "after the video pipeline")
    sentinel.assert_clean("the video pipeline")


def test_ingest_still_copies_and_never_moves():
    """The source-level backstop for the one "optimisation" that would be fatal.

    Ingest reads from the owner's only copy and writes into the app's cache. Turn
    that ``shutil.copy2`` into a ``move``/``rename``/hardlink-plus-unlink and the
    subs stop existing the moment they are ingested — with the app looking, to
    every test that only checks the library, entirely healthy.
    """
    src = (Path(__file__).resolve().parents[2] / "seestack" / "io" / "ingest.py").read_text()
    assert "shutil.copy2(" in src, (
        "ingest no longer copies — it MUST copy out of the incoming folder "
        "(AGENTS.md §10); the owner's raw subs have no second copy.")
    for banned in ("shutil.move(", "os.rename(", "os.replace(", ".rename(",
                   ".replace(", "os.link(", "os.unlink(", ".unlink(",
                   "os.remove("):
        assert banned not in src, (
            f"ingest.py contains {banned!r} — ingest may only *read* the source "
            "frame and *copy* it (AGENTS.md §10).")


def test_the_scanner_only_reads_the_incoming_tree():
    """Same backstop for the module that walks the folder deciding what to do."""
    src = (Path(__file__).resolve().parents[2] / "seestack" / "io" / "scanner.py").read_text()
    for banned in ("shutil.move(", "shutil.rmtree(", "os.rename(", "os.remove(",
                   "os.unlink(", ".unlink(", ".rename("):
        assert banned not in src, (
            f"scanner.py contains {banned!r} — the scanner may only read the "
            "incoming folder (AGENTS.md §10).")
