"""
Generate processing scripts for external astrophoto tools.

The idea: someone takes a Seestack output and wants to continue in Siril or
PixInsight. We emit a tool-specific script that does the standard finishing
steps (color calibration, sharpening, stretch, save). It's a starting point
the user can edit — not a substitute for their own taste.

Two outputs:

  - **Siril** (``.ssf`` script): the open-source standard, runs from Siril's
    Script menu or via the command line.
  - **PixInsight** (``.js`` script): a JavaScript snippet that prints what
    the user should do next, because PixInsight scripting is heavy enough
    that automating the full chain in a one-shot script would do more harm
    than good. Bonus: works as documentation.
"""

from __future__ import annotations

import logging
from pathlib import Path

from seestack.io.project import StackRunRow
from seestack.stack.stacker import StackOptions

log = logging.getLogger(__name__)


def write_siril_script(
    run: StackRunRow,
    options: StackOptions,
    out_path: str | Path,
) -> Path:
    """
    Write a Siril ``.ssf`` script that opens the stack and does a sensible
    post-processing pass: background extraction, color calibration (if not
    already done by Seestack), and an autostretch.

    The script is a plain-text recipe — open in Siril → Scripts → Run script.
    """
    fits_path = run.fits_path or ""
    target_part = f"# Seestack export — {run.output_basename}"
    cc_already_done = options.color_calibration
    lines: list[str] = [
        target_part,
        f"# Generated by Seestack from stack run {run.id} at {run.timestamp_utc}",
        "# Place the master.fits in Siril's working directory, then run this.",
        "",
        f'requires 1.0.0',
        f'load "{Path(fits_path).name}"',
        "",
        "# Remove residual background gradient with object protection.",
        "subsky -rbf -smooth=0.5",
        "",
    ]
    if not cc_already_done:
        lines += [
            "# Photometric colour calibration (uses Siril's catalog lookup).",
            "pcc",
            "",
        ]
    lines += [
        "# Mild stretch for visualisation.",
        "autostretch",
        "",
        f'save "{run.output_basename}_processed.fit"',
        f'savetif "{run.output_basename}_processed.tif"',
        "",
        "close",
    ]
    out_path = Path(out_path)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("Siril script written to %s", out_path)
    return out_path


def write_pixinsight_recipe(
    run: StackRunRow,
    options: StackOptions,
    out_path: str | Path,
) -> Path:
    """
    Write a human-readable PixInsight recipe (commented JavaScript stub).

    A full PixInsight automation isn't worth shipping out of the box — every
    photographer has a different taste for SCNR, deconvolution, and stretch
    parameters. Instead we emit a step-by-step recipe with the recommended
    processes, plus a JS stub that the user can flesh out in the Script
    Editor if they want.
    """
    fits_path = run.fits_path or ""
    cc_done = options.color_calibration
    grad_done = options.final_gradient_removal

    lines = [
        f"// Seestack export — {run.output_basename}",
        f"// Generated from stack run {run.id} at {run.timestamp_utc}",
        f"// Source: {fits_path}",
        "//",
        "// Recommended PixInsight workflow:",
    ]
    step = 1
    if not grad_done:
        lines += [
            f"//   {step}. Process > BackgroundModelization > DynamicBackgroundExtraction",
            "//        place 20–30 samples in sky areas, polynomial degree 2.",
            "//        Subtract the model. (Seestack didn't apply final-stack",
            "//        gradient removal so this is needed.)",
        ]
        step += 1
    if not cc_done:
        lines += [
            f"//   {step}. Process > ColorCalibration > SpectrophotometricColorCalibration",
            "//        runs a Gaia-based colour calibration; produces honest star colours.",
        ]
        step += 1
    lines += [
        f"//   {step}. Process > NoiseReduction > MultiscaleLinearTransform",
        "//        small denoise on the bottom 2 layers, masked to the background.",
        "//   "
        f"   {step + 1}. Process > Stretch > HistogramTransformation",
        "//        use ScreenTransferFunction as the starting curve, then commit.",
        "//   "
        f"   {step + 2}. (Optional) Process > Sharpening > Deconvolution",
        "//        with a star mask. PSF derived from DynamicPSF over ~20 stars.",
        "",
        "// JS stub:",
        "var imageView = ImageWindow.openWindows[0];",
        "if (!imageView) {",
        f'    Console.warningln("Open {Path(fits_path).name} first.");',
        "} else {",
        "    Console.writeln(\"Loaded: \" + imageView.mainView.id);",
        "    // Add Process invocations below as you build your workflow.",
        "}",
    ]
    out_path = Path(out_path)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("PixInsight recipe written to %s", out_path)
    return out_path
